# Use postgres/example user/password credentials
version: '3.1'

services:
  node-example-app:
    build: ../node-example-app/
    restart: always
    environment:
      DATABASE_NAME: knexdb
      POSTGRES_USER: knexuser
      POSTGRES_USER_PW: knexpw
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      NODE_ENV: development
      OTEL_COLLECTOR_TRACES_URL: 'http://otel-collector:4318/v1/traces'
      OTEL_COLLECTOR_METRICS_URL: 'http://otel-collector:4318/v1/metrics'
    ports:
      - 3000:3000
    networks:
      - db
      - otel
  db:
    build: postgres-json-stdout/
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - 5432:5432
    volumes:
      - "./data/knexappdb:/var/lib/postgresql/data/pgdata"
      - "./postgresql.conf:/etc/postgresql/postgresql.conf"
    networks:
      - adminer-network
      - otel
      - fluent-bit
      - db
    logging:
      driver: "fluentd"
      options:
        tag: docker.logify
        fluentd-address: 127.0.0.1:24224
    depends_on:
      - fluent-bit
    attach: false
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - adminer-network
  otel-collector:
    build: otelcol-custom/
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      # - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 4319:4319 # OTLP/example gRPC receiver
      - 55679:55679 # zpages extension
    networks:
      - prometheus
      - otel
      - jaeger
      - fluent-bit
  pgtrace-collector:
    image: elessar1ch/pgtraceconnector:v0.0.1
    volumes:
      - ./pgtraceconnector-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317 # OTLP gRPC receiver
    networks:
      - otel
  fluent-bit:
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluent-bit:/fluent-bit/etc
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    container_name: fluent-bit
    ports:
      - 24224:24224
    networks:
      - fluent-bit
    depends_on:
      - otel-collector
  jaeger:
    image:  jaegertracing/all-in-one:1.52
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 16686:16686
      # - 14317:4317
      # - 14318:4318
    networks:
      - jaeger
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-volume:/prometheus
    ports:
      - 9090:9090
    networks:
      - prometheus
networks:
  adminer-network:
  otel:
  jaeger:
  prometheus:
  fluent-bit:
  db:
volumes:
  prometheus-volume:
    external: false