receivers:
  otlp:
    protocols:
      grpc:
      http:
  postgresql:
    endpoint: db:5432
    transport: tcp
    username: oteluser
    password: otelpw
    databases:
      - knexdb
    collection_interval: 10s
    tls:
      insecure: true
processors:
  logstransform/fluentbitlog:
    operators:
    - type: json_parser
      if: 'body.log matches "^{.*}$"'
      parse_from: body.log
      timestamp:
        parse_from: attributes.timestamp
        layout_type: strptime
        layout: '%Y-%m-%d %H:%M:%S.%L %Z'
    - type: regex_parser
      regex: "traceparent='00-(?P<trace_id>\\S*)-(?P<span_id>\\S*)-(?P<trace_flags>\\d*)'"
      parse_from: body.log
      trace:
        trace_id:
          parse_from: attributes.trace_id
        span_id:
          parse_from: attributes.span_id
        trace_flags:
          parse_from: attributes.trace_flags
  filter/knexuser:
    logs:
      include:
        match_type: strict
        record_attributes:
          - key: user
            value: knexuser
  attributes/loki:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: dbname, user
  # resource/loki:
  #   attributes:
  #     - action: insert
  #       key: loki.resource.labels
  #       value: service.name, service.namespace
exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp/pgtrace:
    endpoint: pgtrace-collector:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: test-space
    const_labels:
      label1: value1
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    add_metric_suffixes: false
    resource_to_telemetry_conversion:
      enabled: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true
connectors:
  forward:
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp, postgresql]
      exporters: [prometheus]
    logs/postgres:
      receivers: [otlp]
      processors: [logstransform/fluentbitlog, filter/knexuser]
      exporters: [otlp/pgtrace, forward]
    logs/loki:
      receivers: [forward]
      processors: [attributes/loki]
      exporters: [loki, debug]
