receivers:
  otlp:
    protocols:
      grpc:
      http:
  postgresql:
    endpoint: db:5432
    transport: tcp
    username: oteluser
    password: otelpw
    databases:
      - knexdb
    collection_interval: 10s
    tls:
      insecure: true
      # insecure_skip_verify: false
      # ca_file: /home/otel/authorities.crt
      # cert_file: /home/otel/mypostgrescert.crt
      # key_file: /home/otel/mypostgreskey.key
processors:
  logstransform/fluentbitlog:
    operators:
      - type: json_parser
        if: 'body.log matches "^{.*}$"'
        parse_from: body.log
  filter/knexuser:
    logs:
      include:
        match_type: strict
        record_attributes:
          - key: user
            value: knexuser
exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    # tls:
      # ca_file: "/path/to/ca.pem"
      # cert_file: "/path/to/cert.pem"
      # key_file: "/path/to/key.pem"
    namespace: test-space
    const_labels:
      label1: value1
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    add_metric_suffixes: false
    resource_to_telemetry_conversion:
      enabled: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp, postgresql]
      exporters: [prometheus]
    logs/postgres:
      receivers: [otlp]
      processors: [logstransform/fluentbitlog, filter/knexuser]
      exporters: [debug]